### ISSUE TITLE
version.json gets cached by browser, update not shown

### ISSUE THREAD

**Issue by formbench** [iamkd/react-update-notification#4]
Hi,

I noticed that the version.json file response that is shown in the developer tools (when caching is on, like it is for most people) contains old data. I was looking for a bug in my build script but it turns out, that it is in fact the browser cache, serving an old version.json, even if the request is made at a regular interval.

This happens on Chrome and Safari for me. 

I suggest a simple change that should fix this issue:

fetch("/" + window.__APP_VERSION_FILE__) → fetch("/" + window.__APP_VERSION_FILE__ + "?" + Date.now())

this should fetch a fresh version of the file every time. Please let me know if this is something that you can implement on a short notice?

**Comment by formbench** [comment]
Hey, is there any update on this? Am I using it wrong? I would appreciate a patch 😀

**Comment by iamkd** [comment]
Hey! Sorry for the delayed response. I've implemented this feature in [v1.1.1](https://github.com/iamkd/react-update-notification/releases/tag/v1.1.1). Please try updating your local version and let me know if it works for you!
